import os

import dotenv
dotenv.load_dotenv()


DATABASE_URL = os.getenv("DATABASE_URL")
ACCESS_TOKEN_EXPIRE_TIME_MINUTES = int(os.getenv("ACCESS_TOKEN_EXPIRE_TIME_MINUTES"))
REFRESH_TOKEN_EXPIRE_TIME_DAY = int( os.getenv("REFRESH_TOKEN_EXPIRE_TIME_DAY"))
ACCESS_TOKEN_SECRET_KEY = os.getenv("ACCESS_TOKEN_SECRET_KEY")
REFRESH_TOKEN_SECRET_KEY = os.getenv("REFRESH_TOKEN_SECRET_KEY")
